### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Playink** [Playink/biletskyi-anton-homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Playink20** [comment]
https://twitter.com/realDonaldTrump
https://www.instagram.com/realdonaldtrump/
https://www.facebook.com/DonaldTrump/
https://en.wikipedia.org/wiki/Donald_Trump
trumpus-crampus.@me.com (trumpus-crampus.@me.com)
