### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Playink** [Playink/biletskyi-anton-homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Playink20** [comment]
### **Skills**
FINANCIAL MANAGEMENT MARKETING BUSINESS SALES CUSTOMER SERVICE COMMUNICATION NEGOTIATION LEADERSHIPPROJECT MANAGEMENT PLANNING DELEGATION TIME MANAGEMENTPROBLEM SOLVINGNETWORKING.
Character
STRONG VERY CONFIDENT PASSIONATE BELIEVING IN GOD LEADER SUSCEPTIBLE AMOROUS RATIONAL PRACTICAL FAIR DEVOTED PEDANTIC CONSISTENT CHALLENGING
### **Likes**😃
BEAUTIFUL WOMEN. MONEY. TWITTER. MY HAIRSTYLE. BUSINESS. MY CHILDREN. WALLS. THE WHITE HOUSE # WILL NEVER BE BLACK GOLF WHITE EMINEM 
### **Dislikes**😞
AMAZON NORTH KOREA KIM JONG-UN BEZOS UGLY WOMEN GRETA THUNBERG 
### **Wants**🥺
MORE MONEYMORE WOMENMORE WALLSLESS LATINOSMAKE AMERICA GREAT AGAINTO BECOME A SUPERHEROMORE FOLLOWERS ON TWITTER
